### ISSUE TITLE
Search results is a POST request

### ISSUE THREAD

**Issue by toolness** [GovLab/noi2#10]
It seems filling out the form at `/search` issues a `POST` request to the same endpoint rather than a GET with querystring parameters.

Aside from being unconventional--since presumably searching for innovators wouldn't change the state of the server--it also means that search results can't easily be shared between users, since the URL doesn't contain any information about the search criteria.

If this is the intended behavior, feel free to close this issue.

**Comment by talos** [comment]
Nope, this looks like a nasty holdover from the old site.  This should definitely be a GET instead of a POST.
