### ISSUE TITLE
Kerning on active tab titles looks weird

### ISSUE THREAD

**Issue by toolness** [GovLab/noi2#112]
On Windows with typekit failing, at least, it looks like this:

![2015-10-08_11-13-03](https://cloud.githubusercontent.com/assets/124687/10370581/92b3e590-6dad-11e5-91c5-1ff071201a54.png)

The unselected tabs look fine, though.

**Comment by talos** [comment]
What IP address is your docker using? Did you do the `/etc/hosts` trick? I think we can have Claudio add whatever is necessary to Typekit to make it work on our dev environments.

**Comment by toolness** [comment]
Yeah, this isn't an issue if typekit is actually loaded, so I'm closing this.
