### ISSUE TITLE
"Join" button in registration step 3 looks kind of disabled

### ISSUE THREAD

**Issue by toolness** [GovLab/noi2#116]
In the original mockups for registration step 3, a "Join" button at the bottom of the page is disabled until the user answers at least 3 questions. However, in @claudioccm's style-guide mockups, there is no "Join" button at all, so right now the "Join" button added in #94 is completely unstyled.

My guess is that claudio thinks that once the user answers their third question, they should immediately be sent to the activity page, rather than having to click "Join". I'm fine with this, though it should be noted that without an explicit "Join" button, the user can't just continue to answer questions if they feel like they're on a roll or something. :)

**Comment by talos** [comment]
I think we should have an explicit Join button so that users can keep answering questions! @claudioccm

**Comment by claudioccm** [comment]
if you add `.b-button` you should have your styles in place. If not, I will
take care of it

**Comment by toolness** [comment]
The "Join" button could be styled like the "Next" button in #166, so it'd be great if they could share the same CSS class.
