### ISSUE TITLE
Implement "radar" visualization on public user profile

### ISSUE THREAD

**Issue by talos** [GovLab/noi2#125]
https://trello.com/c/xidfCc82/13-my-profile-overview

<img width="364" alt="screen shot 2015-10-19 at 8 28 15 pm" src="https://cloud.githubusercontent.com/assets/124687/10594905/0ae26136-76a0-11e5-9f3a-5f63d27f0906.png">

This requires:
- [ ] A server-side method to provide the required data
- [ ] Client-side code to generate the visualization (probably using D3)

**Comment by talos** [comment]
Dupe of #125, this is what we use *for* the radar.

**Comment by talos** [comment]
Duplicate of #125

**Comment by toolness** [comment]
Uh, alternatively, the radar might look like this:

<img width="416" alt="screen shot 2015-10-19 at 8 36 15 pm" src="https://cloud.githubusercontent.com/assets/124687/10595043/8c8a8064-76a1-11e5-9444-0357a1780a04.png">
