### ISSUE TITLE
dropdown component

### ISSUE THREAD

**Issue by claudioccm** [GovLab/noi2#134]
I created a second version of the dropdown component. I wanted to replace the one we had there already, but you were already using it on the _macros_new.html

I got worried about incompatibility between my screens and the ones you already implemented. 
We can talk about this tomorrow.

This is the structure of the new version. 
``` <label class="b-dropdown-alt" for="">
     <select>
         <option></option>
     </select>
 </label>```

**Comment by toolness** [comment]
This was fixed by #137.
