### ISSUE TITLE
Registration process doesn't ultimately take the user to the URL they originally wanted to visit

### ISSUE THREAD

**Issue by toolness** [GovLab/noi2#142]
I believe flask-security is built in such a way that once users register on the site, they are redirected to the page that they originally wanted to go to, if any.

For instance, if the user clicked on "match me" and was taken to the login page, and then logged in, they would be redirected to the "match me" page. *Theoretically* the same thing ought to happen if the user clicks "sign up" on the login page and goes through the whole registration flow, but it currently doesn't.

I'm thinking that because the registration flow is rather involved, the user will probably forget what they originally clicked on to arrive at the login screen in the first place; furthermore, it seems like taking the user to the activity stream and showing them the first tutorial pop-up is actually the optimal behavior, rather than taking the user to what they originally clicked on, which may even be confusing for users.

So I'm hoping we can just mark this issue as WONTFIX. :grin:

**Comment by talos** [comment]
I would agree with WONTFIX for the registration -- obviously not for login.  Everything is OK for login?

**Comment by toolness** [comment]
Yup everything is OK for login! Closing this issue.
