### ISSUE TITLE
Change "es_MX" locale to just "es"

### ISSUE THREAD

**Issue by toolness** [GovLab/noi2#172]
As mentioned in #171:

> ![2015-10-20_9-02-20](https://cloud.githubusercontent.com/assets/124687/10607716/62a03092-7709-11e5-82bd-df5616aeca3b.png)
>
> The `es_MX` is apparently because that locale has a ['display_name`](http://babel.pocoo.org/docs/api/core/#babel.core.Locale.display_name) of `None`, so I'm falling back to the locale code.

**Comment by toolness** [comment]
Just talked to @mphermosilla about this and it looks like her and @itelloarista have translated the text such that it's as widely-understandable as possible to Spanish speakers, and not Mexico-specific.

So we should really change "es_MX" to "es", so that it will show up as "Espanol" in the language menu, and so that user agents with spanish `Accept-Language` headers are more likely to see spanish-language versions of the site by default, without needing to use the language selector widget.

**Comment by itelloarista** [comment]
Completely agree. Hope you can add the ñ to Español in the webpage.

**Comment by toolness** [comment]
Ah yup, we will, I just didn't add it in the Github comment because I didn't know how to type it :grin:
