### ISSUE TITLE
Remove extraneous vendor-prefixed flexbox CSS from SASS

### ISSUE THREAD

**Issue by toolness** [GovLab/noi2#196]
Now that we're using the CSS autoprefixer, we don't need it.

**Comment by toolness** [comment]
Hey @claudioccm would you mind taking care of this one real quick, just to clean up our CSS a bit? It basically just involves reverting 3f5222f3d24abecd3d4294bd2a2a06a78eab39a2 and any other vendor-prefixed flexbox CSS you might've added since then.

**Comment by toolness** [comment]
Hey @mocxd do you want to try doing this one? It'd be a great "first bug" to get you acquainted w/ setting up the development environment and changing the SASS files.

**Comment by mocxd** [comment]
sounds good!

**Comment by mocxd** [comment]
https://github.com/GovLab/noi2/pull/279#issuecomment-183000780
