### ISSUE TITLE
Add new Spanish translations

### ISSUE THREAD

**Issue by toolness** [GovLab/noi2#205]
Since our last translation merge in #189, we've had some new content come in:

* [Invite email](https://github.com/GovLab/noi2/blob/921ce819ecd5dd69cd8dd99265185035cb9d6748/app/translations/es/LC_MESSAGES/messages.po#L322-L332)
* [Multi-select instructions](https://github.com/GovLab/noi2/blob/921ce819ecd5dd69cd8dd99265185035cb9d6748/app/translations/es/LC_MESSAGES/messages.po#L463-L467)
* Everything in the [About page](https://github.com/GovLab/noi2/blob/921ce819ecd5dd69cd8dd99265185035cb9d6748/app/translations/es/LC_MESSAGES/messages.po#L525-L618)
* Everything in the [FAQ](https://github.com/GovLab/noi2/blob/921ce819ecd5dd69cd8dd99265185035cb9d6748/app/translations/es/LC_MESSAGES/messages.po#L683-L886)
* Everything in the [landing page](https://github.com/GovLab/noi2/blob/921ce819ecd5dd69cd8dd99265185035cb9d6748/app/translations/es/LC_MESSAGES/messages.po#L909-L981)
* The [RCTS Questionnaire](https://github.com/GovLab/noi2/blob/921ce819ecd5dd69cd8dd99265185035cb9d6748/app/translations/es/LC_MESSAGES/messages.po#L2924-L3058)

There are also a few others, like the new descriptions for all the innovation areas, which were added in 8e5d528e89242e9cd678bbaae2ed755ed1a31346. These don't seem to all be located in one place in the `.po` file, unfortunately.

**Comment by toolness** [comment]
Here's the translations to the RCTS questionnaire that @mphermosilla did, but because I don't have the English version, I'm not sure how to map them to the proper lines in the `.po` file:

[RCTQuestionnaire_ESMariaReviewed.docx](https://github.com/GovLab/noi2/files/21095/RCTQuestionnaire_ESMariaReviewed.docx)

**Comment by toolness** [comment]
@mphermosilla, is there any way you can help with these? It might actually be easiest for you to [download the `.po` file](https://raw.githubusercontent.com/GovLab/noi2/921ce819ecd5dd69cd8dd99265185035cb9d6748/app/translations/es/LC_MESSAGES/messages.po) and edit it with something like [Poedit](https://poedit.net/), rather than manually doing it like you did before--I suspect Poedit has some functionality that allows you to easily find all the untranslated strings, for example, which is difficult to do when you edit the `.po` file on GitHub...

Sorry this is so last minute!

**Comment by mphermosilla** [comment]
Hi!
I could only look at this tonight around 10.30 pm.
Let me know if that is useful at that time.
And if so, it would be great to connect with you on slack at that time
because I don't understand the instructions that much.
Regards,
Maria

**Comment by toolness** [comment]
Ok, I won't be able to be on slack that late, so here are some basic instructions--if you run into problems, don't worry about it:

1. Download our Spanish `messages.po` file by visiting https://raw.githubusercontent.com/GovLab/noi2/921ce819ecd5dd69cd8dd99265185035cb9d6748/app/translations/es/LC_MESSAGES/messages.po and going to "File -> Save Page As..." in your browser. Save it as `messages.po` on your Desktop.
2. Download Poedit at https://download.poedit.net/Poedit-1.8.6.zip. Double-click on it and open the Poedit app contained within.
3. From the Poedit main window, choose "Edit a translation" and open the `messages.po` file on your Desktop.
4. You should see a window that looks something like this:
  <img width="561" alt="screen shot 2015-10-26 at 10 49 29 pm" src="https://cloud.githubusercontent.com/assets/124687/10748175/e27d9a32-7c33-11e5-85d4-e0bf8e0e9151.png">
5. Find the text strings that have no spanish translations (i.e., where the right column is empty) and fill them in by typing in the "Translation" field at the bottom of the window. You can press Command-S to save the file as you work.
6. When you're done, save the file and send it to me by uploading it to Slack.

**Comment by toolness** [comment]
Done as of 9cc13b78490f94fcb6ad43e46ed12fd827b54b4a.
