### ISSUE TITLE
UniqueConstraints in models.py don't do anything

### ISSUE THREAD

**Issue by toolness** [GovLab/noi2#21]
When attempting to add a test that verifies the `UniqueConstraint` in the `User` model was working, I think I discovered that it doesn't work.

Currently `models.py` declares unique constraints like this:

```python
class User(db.Model, UserMixin):
    constraint = UniqueConstraint('deployment', 'email')
```

However, according to the SQLAlchemy documentation, we should be declaring such constraints as part of the [table configuration](http://docs.sqlalchemy.org/en/rel_0_7/orm/extensions/declarative.html#table-configuration):

```python
class User(db.Model, UserMixin):
    __table_args__ = (UniqueConstraint('deployment', 'email'),)
```

This can be verified by adding a new test file at `app/tests/test_model_uniqueness.py`:

```python
from flask import Flask
from flask.ext.testing import TestCase
from sqlalchemy.exc import IntegrityError

from .. import models

db = models.db

class DbTest(TestCase):
    def create_app(self):
        app = Flask('test')
        app.config['TESTING'] = True
        app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite://'
        app.config['NOI_DEPLOY'] = '_default'
        db.init_app(app)
        return app

    def setUp(self):
        db.create_all()

    def tearDown(self):
        db.session.remove()
        db.drop_all()

class MyTest(DbTest):
    def test_ensure_user_is_constrained_by_deployment_and_email(self):
        a1 = models.User(email=u'a@example.org', password='a', active=True,
                         deployment='1')
        a2 = models.User(email=u'a@example.org', password='a', active=True,
                         deployment='2')
        db.session.add(a1)
        db.session.add(a2)
        db.session.commit()

        with self.assertRaises(IntegrityError):
            a1 = models.User(email=u'a@example.org', password='u',
                             active=True, deployment='1')
            db.session.add(a1)
            db.session.commit()
```

Running `./nosetests` should cause this test to fail with `AssertionError: IntegrityError not raised` unless the aforementioned change is made to the model.

**Comment by talos** [comment]
Yep, this was done wrong before.  Thankfully this code hasn't been deployed yet, so we shouldn't be in a situation where duplicate accounts were created in production.

Could you please make the code change, and generate the appropriate migration?
