### ISSUE TITLE
post an update send button

### ISSUE THREAD

**Issue by chrswng** [GovLab/noi2#229]
if the message is longer than the text box, you have to push send once to resize the box and then send again to actually send.

**Comment by toolness** [comment]
Hmm, one potential solution is to set `resize: none` on the textarea, so that it can't be resized.

**Comment by chrswng** [comment]
unable to reproduce this error in dev, i'll ask batu to see if he can show me tomorrow

**Comment by toolness** [comment]
This doesn't seem to be a reproducible issue so I'm closing it.
