### ISSUE TITLE
Add a decent NoI logo for LinkedIn integration

### ISSUE THREAD

**Issue by toolness** [GovLab/noi2#293]
This is the lame one I've currently submitted:

![2016-03-07_14-46-13](https://cloud.githubusercontent.com/assets/124687/13581124/6635e7ba-e473-11e5-9512-e915d3ab1bcd.png)

It looks like this when users authenticate with LinkedIn:

![2016-03-07_14-44-52](https://cloud.githubusercontent.com/assets/124687/13581141/6dd0c224-e473-11e5-839a-faecdc4f70a9.png)

**Comment by chrswng** [comment]
<img width="256" alt="noi-avatar" src="https://cloud.githubusercontent.com/assets/8985721/13828646/ed729eea-eb98-11e5-86cd-30ed93ea048d.png">

**Comment by toolness** [comment]
Ok just changed it!
