### ISSUE TITLE
Open links to discourse in the same tab

### ISSUE THREAD

**Issue by toolness** [GovLab/noi2#298]
In our meeting on Discourse integration w/ @batusayici, I think that we decided to just open all Discourse links in the same tab, rather than a separate one. Rationale:

* As the Discourse is a NoI property, it's not 100% "external" in some sense, so we can treat it like other internal links.
* When a user posts to Discourse, if they have their activity feed open in a separate tab, they won't actually see the post immediately appear in their activity feed, because the feed page doesn't use websockets or long polling to update itself in real-time. Having Discourse open in the same tab greatly reduces the likelihood that the user will have their activity feed open in a separate tab.

Note, however, that this solution *does* necessitate that we have a link back to NoI in the header of the Discourse site--otherwise it will be difficult for users to go back to NoI.

@batusayici can you verify that this is the desired behavior?

**Comment by batusayici** [comment]
Correct! Thanks for doublecheck
