### ISSUE TITLE
add back to NOI icon to Discuss UI

### ISSUE THREAD

**Issue by batusayici** [GovLab/noi2#300]

**Comment by toolness** [comment]
Just added this under [`/admin/customize/css_html/1/header`](http://discourse-dev.networkofinnovators.org/admin/customize/css_html/1/header):

```html
<div style="background: #f0f0f0; padding: 10px">
  <a href="https://noi-demo.thegovlab.org">&laquo; Go back to Network of Innovators</a>
</div>
```

It looks like this on the site:

![go-back-to-noi](https://cloud.githubusercontent.com/assets/124687/13967047/a889bd1a-f04b-11e5-8b1d-0f56981377b0.png)

**Comment by toolness** [comment]
Oh, it looks like Discourse uses a completely separate header for mobile, so I had to copy-paste the same HTML to [`/admin/customize/css_html/1/mobile-header`](http://discourse-dev.networkofinnovators.org/admin/customize/css_html/1/mobile-header).
