### ISSUE TITLE
Set up authentication for new discourse instance

### ISSUE THREAD

**Issue by naffis** [GovLab/noi2#313]

**Comment by mocxd** [comment]
can you clarify?

**Comment by chrswng** [comment]
@mocxd  I think this issue was created before the conversation with @toolness about how the auth works. i think at this point its just running @toolness's script when the discourse prod is ready to be connected

**Comment by naffis** [comment]
Correct. The pages and logic for the auth process is already set up. We simply need to configure the prod app with the keys and endpoints for discourse.
