### ISSUE TITLE
UserEvents may not be deleted when their related Users are

### ISSUE THREAD

**Issue by toolness** [GovLab/noi2#32]
One of the nice things I've noticed about the `User` model is that rows in related tables like expertise domains, languages, and skills are automatically removed when users are deleted via `cascade='all,delete-orphan'`. This isn't specified for the `UserEvent` model introduced in #27, though, which could mean that those events hang around even when users are deleted.

Might be good to add a test case to verify this and fix the behavior if necessary.

**Comment by talos** [comment]
Good catch.  We should be using those cascade rules, and chances are we aren't deleting upon user deletion.

On the upside, this isn't super-high priority as there's no support for programatically deleting users anyway.

**Comment by talos** [comment]
@AnupamaSh can you please add the appropriate cascade rules to `models.py`?

**Comment by AnupamaSh** [comment]
Sure.

user = orm.relationship('User',backref=backref('events',
                         uselist=True,
                         cascade='delete-orphan,all'))  

Adding the following in userEvent might fix this.

**Comment by talos** [comment]
@AnupamaSh can you make that change for all cascade rules, as well as appropriate tests?
