### ISSUE TITLE
landing page news section

### ISSUE THREAD

**Issue by chrswng** [GovLab/noi2#350]
copy:

"Get access to stories written and curated specifically for Network of Innovators users!"

There's also font styling issue between this and the other section headers

**Comment by mocxd** [comment]
<img width="1280" alt="screen shot 2016-07-02 at 8 52 13 am" src="https://cloud.githubusercontent.com/assets/1042629/16540427/3f1eac8c-4032-11e6-8611-c160662f6d21.png">
<img width="1276" alt="screen shot 2016-07-02 at 8 52 07 am" src="https://cloud.githubusercontent.com/assets/1042629/16540428/3f21d6dc-4032-11e6-9227-51cc9649e189.png">

**Comment by mocxd** [comment]
font style looks the same what or is this 4k vision?

**Comment by chrswng** [comment]
<img width="1170" alt="screen shot 2016-07-02 at 1 07 11 pm" src="https://cloud.githubusercontent.com/assets/8985721/16541668/ddf5800a-4056-11e6-8319-4117af773ca2.png">

should look like this. SHould say News, in same style as Visualize your knowledge

**Comment by mocxd** [comment]
oh ic
