### ISSUE TITLE
add scroll to slider menu

### ISSUE THREAD

**Issue by chrswng** [GovLab/noi2#351]
we had this problem with www too

**Comment by mocxd** [comment]
works for me? confused

**Comment by chrswng** [comment]
doesn't work for me. is this a browser problem or a personal problem?

**Comment by mocxd** [comment]
what browser r u using, chrome?

**Comment by mocxd** [comment]
yeah i sent a gif of it working on my browser... i thought my laptop screen was smaller than urs as well

**Comment by mocxd** [comment]
can anyone else try it and try to get more information about screen size/ browsers re whether it works or not

**Comment by mocxd** [comment]
unfortunately i only have the one laptop rn

**Comment by mocxd** [comment]
nvm i see it, it's only on remote
