### ISSUE TITLE
Translations update

### ISSUE THREAD

**Issue by chrswng** [GovLab/noi2#366]
https://docs.google.com/document/d/1Er2JQ_-AjamByKNTtjiCPNC_tflRP_iOuoGL2TD0H1I/edit?ts=577d02cb#

This is apparently final now

Specific things to note:
Edit Profile
Discuss button (Foro shouldn't be capitalized)
Will be a change to the Find Innovators button translation

**Comment by mocxd** [comment]
this is all probably fixed just want to confirm
