### ISSUE TITLE
User.nearest_neighbors and User.helpful_users don't filter by deployment

### ISSUE THREAD

**Issue by toolness** [GovLab/noi2#38]
As mentioned in #36, the following methods need to filter users by deployment:

- [x] `User.nearest_neighbors`
- [x] `User.helpful_users`
- [x] `User.get_most_complete_profiles()` (This can't be done until #36 lands)

**Comment by talos** [comment]
Still haven't fixed `User.get_most_complete_profiles()`.  Reopening & handling.

**Comment by toolness** [comment]
I think this is done now, right?

**Comment by talos** [comment]
Good catch, the last checkbox was filled by https://github.com/GovLab/noi2/pull/56.
