### ISSUE TITLE
Client-side SyntaxError on page load at /feedback

### ISSUE THREAD

**Issue by toolness** [GovLab/noi2#47]
At least when `config.contact_form_id` isn't defined, this results in malformed JS which causes the JS on this page to crash with a `SyntaxError`.

What should the appropriate behavior here be? We could give `config.contact_form_id` a default value, or we could disable the feedback form entirely when it's not defined, but causing a `SyntaxError` seems confusing for developers and users alike.

**Comment by talos** [comment]
@AnupamaSh can you look into this?

**Comment by AnupamaSh** [comment]
@talos would you know what the correct project_id is? 1246 returns {"error":"project not found"}

**Comment by talos** [comment]
Turns out we're moving from ScreenDoor to Google Forms.  Closing this and making a new issue.

**Comment by talos** [comment]
We're using https://the-govlab.forms.fm/network-of-innovators-feedback/, project_id `1739`.

**Comment by talos** [comment]
This was resolved with 44c344902904cf0477a5a44dd71b3f3f7e606766.
