### ISSUE TITLE
Direct users to complete registration process if they haven't yet

### ISSUE THREAD

**Issue by toolness** [GovLab/noi2#49]
As mentioned in #43, we need to be able to redirect the user to complete the registration process depending on where they are in it.

More specifically, we mean that if the user has less than `MIN_QUESTIONS_TO_JOIN` skills, they haven't yet completed registration. If they have at least 1 skill *or* has filled out *any* of the questions in part 2 of registration, redirect them to step 3. Otherwise, redirect them to step 2.

**Comment by toolness** [comment]
Hmm, I just realized that there's potentially another way to detect whether a user has completed registration...

Currently in our mockups, we've got an implicit event type for remembering when a user "joined NOI":

![2015-09-29_16-41-33](https://cloud.githubusercontent.com/assets/124687/10177640/1f22d7ca-66c9-11e5-9226-b22dda265346.png)

We haven't yet implemented this event type, but we could potentially have it double as a sentinel for when the registration process is complete. If we went this route, we'd want the final "Join" button to be an actual POST rather than a simple link to `/activity`, so that the event could be created... Actually, even if we *don't* use the event as a sentinel, we'll probably want to do this regardless--otherwise I'm not sure when we'd generate the event.

**Comment by talos** [comment]
I like that idea!

**Comment by toolness** [comment]
This is now superseded by #59.
