### ISSUE TITLE
README assumes boot2docker

### ISSUE THREAD

**Issue by toolness** [GovLab/noi2#5]
It seems in August 2014, boot2docker was replaced with [Docker Toolbox](http://blog.docker.com/2015/08/docker-toolbox/), which uses [Docker Machine](https://docs.docker.com/machine/) instead of boot2docker for managing VMs.

This means, for example, that instead of `boot2docker ip`, one should run `docker-machine ip default` (though the last argument may be different for each user).

I'm not sure if the README should still include instructions for folks who are still on boot2docker or not though.

**Comment by talos** [comment]
Interesting.  Good move on their part, as `boot2docker` is deeply problematic.

The change happened in August 2015, which explains the dependency -- this work was done in earnest just before their announcement, and as I do sometimes develop with Mac I was used to boot2docker.

Let's talk about this tomorrow.
