### ISSUE TITLE
On non-production deploys, consider defaulting DEBUG to True

### ISSUE THREAD

**Issue by toolness** [GovLab/noi2#6]
It's easy enough for devs to figure out on their own, I suppose, but to lower the barrier to entry for potential contributors, you may want to actually default `DEBUG: True` in `config.yml`, or at least encourage developers to include that line in their `local_config.yml` in the README, as developing the app isn't particularly developer-friendly without it.

**Comment by talos** [comment]
Agreed.  I can take care of this, although if you want to flip it I'll most definitely merge.
