### ISSUE TITLE
Add Content Security Policy

### ISSUE THREAD

**Issue by toolness** [GovLab/noi2#70]
[Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/Security/CSP/Introducing_Content_Security_Policy) is a great way to safeguard modern browsers against XSS attacks. The main thing that makes it hard to implement in legacy sites is inline scripts, but especially after #65 it seems like we don't have a lot of that, so it shouldn't be hard to migrate it over to separate script files. And once CSP is in place, it's pretty easy to keep around.

The only major end-user downside of CSP is that it sorta breaks bookmarklets.

**Comment by talos** [comment]
Makes a lot of sense.  I'm fine with breaking bookmarklets; if someone really wants one to work, we can just add it to our policy, no?
