### ISSUE TITLE
Set up a US NoI

### ISSUE THREAD

**Issue by talos** [GovLab/noi2#71]
We need a basic NoI install at https://us.networkofinnovators.org

@toolness , @AnupamaSh , I can train you on doing this ASAP.

**Comment by talos** [comment]
Up and running at https://usg.networkofinnovators.org .

Documentation is on the [wiki](https://github.com/GovLab/noi2/wiki/Setting-up-an-NoI-Instance).

**Comment by toolness** [comment]
Thanks @talos!

Do you think we could move the docs from the wiki to a `DEPLOYING.md` in the repository? I think it's a lot more likely to stay up-to-date if it's closer to the code it's describing, but that's just my 2 cents.

**Comment by talos** [comment]
Sure. Do you think it makes sense to have a `docs` directory?

**Comment by toolness** [comment]
Cool!

For now I think just putting the file in the root dir is fine, but if/when we have more markdown files in there, moving to a `docs` directory would be a good idea.

**Comment by talos** [comment]
Done with https://github.com/GovLab/noi2/commit/67d6afc734e6e556ea7bc8828842d5c259c87ef9 .
