### ISSUE TITLE
Integrate noi-ui into login/registration

### ISSUE THREAD

**Issue by talos** [GovLab/noi2#74]
On the `ui` branch, from https://github.com/claudioccm/noi-ui/

**Comment by toolness** [comment]
Should the activity feed also be styled as per his [activity.html](https://github.com/claudioccm/noi-ui/blob/master/site/activity.html), or are we holding off on that for now?

Also, do you think the SASS directory should have its own README or anything? Claudio mentioned this intro to his SASS/CSS naming style on Slack, which I found useful:

```
ok, here goes a 101
my classes are prefixed by one of 3 letters
.b-classname, .e-classname or .m-classname (edited)
.b-classname are blocks that exist in the global scope
.e-classname only exists inside a .b-class
this prevents most of the style conflicts
and makes naming much easier, hehe
.e- stands for element
.m-classname stands for Modifier, and they only exist when coupled with another .b- or .e-
.b-textfield.m-invalid
this is the class for the invalid input element
this generates the red text 
```

**Comment by talos** [comment]
The activity feed should be, but let's focus on turning out login/register for now and do that separately.

Sure -- let's copy that into the wiki!

**Comment by toolness** [comment]
Oh, this has been done by #79 and #91.
