### ISSUE TITLE
Remove font awesome CSS from new UI

### ISSUE THREAD

**Issue by toolness** [GovLab/noi2#81]
As mentioned in #79:

> The new base template is including *both* [Google Material Icons](https://www.google.com/design/icons/) *and* [Font Awesome](http://fortawesome.github.io/Font-Awesome/); are we really using both? (I definitely see the material icons in claudio's HTML source, but haven't seen any FA yet.)

I've done a grep for `fa-` and `awesome` in [claudioccm/noi-ui](https://github.com/claudioccm/noi-ui) and the only thing it's turned up is the `<link>` tag for font awesome, so it definitely *seems* like it's not being used...

@claudioccm, if you can confirm this, I'll go ahead and remove that link tag from the new UI's base template.

**Comment by claudioccm** [comment]
Let's delete it. The only issue is social media icons, but I can figure a better solution for that if we absolutely need that.
