### ISSUE TITLE
Document how best to connect to local dev instance

### ISSUE THREAD

**Issue by toolness** [GovLab/noi2#84]
Currently we have a line in our nginx configuration that disables HTTPS if the server is accessed directly via an IP address, which makes it convenient to access the server when it's in a docker container/VM on OS X or Windows.

However, as mentioned in #79, TypeKit doesn't seem to like this... So we should probably figure out the best practice for connecting to our local dev machines and document it in the README.

**Comment by talos** [comment]
I'm in favor of adding a line to `/etc/hosts` that links to the `boot2docker ip`:

```
<boot2docker ip> boot2docker
```

We would then need to add `boot2docker` to our Typekit permissions.

**Comment by toolness** [comment]
That sounds good to me (`s/boot2docker/docker-machine`, of course :grin:). Should we also change the nginx config to not disable HTTPS if the machine is accessed purely over an IP address? I actually wonder if that's a security vulnerability...

**Comment by talos** [comment]
Hmm, I suppose it could be a security vulnerability.
