### ISSUE TITLE
Version our docker image

### ISSUE THREAD

**Issue by talos** [GovLab/noi2#90]
Since we now have an [automated build](https://hub.docker.com/r/thegovlab/noi2/) on Docker Hub, we should version the image in our Dockerfile.

**Comment by talos** [comment]
It looks like we can't manually tag our image on Docker Hub, but we *can* tag it via git tags or branches:

http://stackoverflow.com/questions/25328166/docker-hub-automated-build-tagging

This is actually pretty nice.  By default, `master` is mapped to the `:latest` tag (the default) on Docker.  If we wanted, we could instead map it to a manually set `docker` tag in GH.  We can talk about this tomorrow.

**Comment by talos** [comment]
This is tricky.  I've set `.travis.yml` to `docker-compose pull` before running tests, but this still depends on having had `master` build with the latest image before tests run, if tests depend on a new image.

What do you think @toolness ?  Should we have a separate branch, like `image`, linked to :latest ? That would at least give us a little more control over the process than having to put images on `master`.

**Comment by toolness** [comment]
This has been done by #244.
